modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"


[[mods]]
modId = "paxeljs"
version = "${version}"
displayName = "PaxelJS"
description = '''Adds Paxel tool type to KubeJS'''
[[dependencies.paxeljs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.paxeljs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.paxeljs]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.paxeljs]]
modId = "cucumber"
mandatory = true
versionRange = "[7.0.7]"
ordering = "NONE"
side = "BOTH"